# Generated by Django 2.1.5 on 2019-01-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_post_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
