# Generated by Django 2.1.5 on 2019-01-19 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20190120_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='amount',
        ),
    ]
