# Generated by Django 2.1.5 on 2019-01-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_post_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
