# Generated by Django 2.1.5 on 2019-01-19 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20190120_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='amount',
        ),
    ]
